employee_name = input('employee name :')
ssn: str = input('enter ssn :')
phone_number = input('enter phone number :')
email = input('enter email :')
salary = input('enter salary :')
print(employee_name)
print('ssn: '+ ssn)
print('phone_number: '+ phone_number)
print('email: '+ email)
print('salary: '+ salary)
